stages:
  - build
  - test

variables:
  BUILD_DIR: build
  DEBIAN_FRONTEND: noninteractive

cache:
  key: qt-cache
  paths:
    - /usr/local/qt6  
    - $BUILD_DIR     

build:
  stage: build
  image: ubuntu:22.04
  before_script:
    - apt-get update && apt-get install -y cmake build-essential git wget
    - if [ ! -d /usr/local/qt6 ]; then
        apt-get install -y qt6-base-dev;
      fi
  script:
    - mkdir -p $BUILD_DIR
    - cd $BUILD_DIR
    - cmake -S ../AlgoVision -B . -DCMAKE_BUILD_TYPE=Release
    - cmake --build .
  artifacts:
    paths:
      - $BUILD_DIR
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push"' 

run_tests:
  stage: test
  image: ubuntu:22.04
  before_script:
    - apt-get update && apt-get install -y cmake build-essential qt6-base-dev
  script:
    - cd $BUILD_DIR
    - ctest --output-on-failure
  dependencies:
    - build
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push"'  