stages:
  - build
  - test

variables:
  BUILD_DIR: build

build:
  stage: build
  image: qt:6.6.2-base
  script:
    - mkdir -p $BUILD_DIR
    - cd $BUILD_DIR
    - cmake -S ../AlgoVision -B . -DCMAKE_BUILD_TYPE=Release
    - cmake --build .
  artifacts:
    paths:
      - $BUILD_DIR
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push"' 

run_tests:
  stage: test
  image: qt:6.6.2-base
  script:
    - cd $BUILD_DIR
    - ctest --output-on-failure
  dependencies:
    - build
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push"'  